tsm:
  api:
    base-url: "https://pricing-api.tradeskillmaster.com/ah/"
  auction-house-to-sell:
    eu-silvermoon: 160
  scanned-realms:
    - "Uldaman"
    - "Ysera"
    - "Moonglade"
    - "Arthas"
    - "Blackrock"
    - "Lightbringer"
    - "Azuremyst"
    - "Norgannon"
    - "Hyjal"
    - "Draenor"
    - "Galakrond"
    - "Chromaggus"
    - "Zuluhed"
    - "Blade's Edge"
    - "Hellfire"
    - "Gordunni"
    - "Outland"
    - "Suramar"
    - "Chamber of Aspects"
    - "Nordrassil"
    - "Spinebreaker"
    - "Genjuros"
    - "Exodar"
    - "Shadowsong"
    - "Ysondre"
    - "Archimonde"
    - "Stormscale"
    - "Todeswache"
    - "Zul'jin"
    - "Auchindoun"
    - "Ragnaros"
    - "Tyrande"
    - "Turalyon"
    - "Un'Goro"
    - "Pozzo dell'Eternità"
    - "Quel'Thalas"
    - "Anetheron"
    - "Rexxar"
    - "Arak-arahm"
    - "Lothar"
    - "Echsenkessel"
    - "Argent Dawn"
    - "Fordragon"
    - "Ashenvale"
    - "Alexstrasza"
    - "Die Aldor"
    - "Khaz Modan"
    - "Magtheridon"
    - "Eredar"
    - "Deathguard"
    - "Arathi"
    - "Soulflayer"
    - "Nefarian"
    - "Dragonblight"
    - "Howling Fjord"
    - "Thrall"
    - "Silvermoon"
    - "Wildhammer"
    - "Khaz'goroth"
    - "Nemesis"
    - "Dun Modr"
    - "Garrosh"
    - "Blackmoore"
    - "Ravencrest"
    - "Marécage de Zangar"
    - "Burning Legion"
    - "Azuregos"
    - "Frostwolf"
    - "Antonidas"
    - "Twisting Nether"
    - "Goldrinn"
    - "Garona"
    - "Elune"
    - "Vol'jin"
    - "Khadgar"
    - "Eversong"
    - "Aegwynn"
    - "Die ewige Wacht"
    - "Grim Batol"
    - "Aggramar"
    - "Kul Tiras"
    - "Blackscar"
    - "Emeriss"
    - "Malygos"
    - "Kor'gall"
    - "Confrérie du Thorium"
    - "Drak'thul"
    - "Kazzak"
    - "Dentarg"
    - "Sporeggar"
    - "Terenas"
    - "Dethecus"
